### ISSUE TITLE
But this Is O(N) shift

### ISSUE THREAD

**Issue by james4388** [john-ko/data-structures#1]
@john-ko 
https://github.com/john-ko/data-structures/blob/818390958f5bf37ff81859755418ca847470c506/src/Queue/Queue.ts#L14

Why not use your LinkedList (or double LinkedList)

**Comment by john-ko** [comment]
^^; added a linked list as queue, and shift as O(1) operation

https://github.com/john-ko/data-structures/blob/bb28f82b303c31ec0416bbe67b83902375ce8c51/src/queue/queue.ts#L1-L25

**Comment by james4388** [comment]
And you can use a circular array for the queue too, have two pointer chasing each other is fun.
