### ISSUE TITLE
Fibo recursive is not O(n^2)

### ISSUE THREAD

**Issue by james4388** [john-ko/data-structures#2]
https://github.com/john-ko/data-structures/blob/30a208044bae3dcd8762c5e4f8e20e6df20f221b/src/fibonacci/fibonacci.ts#L10

Let see why. Let try `fibo(5)` and see what happen in the call stack:
```
                              fib(5)
                           /           \
                  fib(4)       +        fib(3)
              /           \              /         \
          fib(3)  + fib(2)  fib(2) + fib(1)
        /         \
     fib(2) + fib(1)

```
Basically at each branch you have two choice (two other call) until you reach a known value (2 or 1) so we can say worst case time complexity is O(2^n) or just say exponential

**Comment by john-ko** [comment]
@james4388 ah your right. let me update docs

**Comment by john-ko** [comment]
updated! ![formula](https://render.githubusercontent.com/render/math?math=O(2^n))
